### ISSUE TITLE
A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by h-teske** [zource-dev/litra-glow#1]
Hi, would love to use your app to control my litra glow. Unfortunately I get the following error when opening it on my Mac:

`Uncaught Exception:
Error: LIBUSB_ERROR_ACCESS
at Interface.detachKernelDriver (/private/var/folders/jy/v11m1wcx015dg8vryv8fcdy80000gn/T/AppTranslocation/D9BF59BE-C131-4919-A5CD-9B0B3E1DCCA7/d/litra.app/Contents/Resources/app.asar/node_modules/usb/tsc/usb/interface.ts:127:28)
at new t.default (/private/var/folders/jy/v11m1wcx015dg8vryv8fcdy80000gn/T/AppTranslocation/D9BF59BE-C131-4919-A5CD-9B0B3E1DCCA7/d/litra.app/Contents/Resources/app.asar/dist/main/main.js:2:443560)
at Object.t.create (/private/var/folders/jy/v11m1wcx015dg8vryv8fcdy80000gn/T/AppTranslocation/D9BF59BE-C131-4919-A5CD-9B0B3E1DCCA7/d/litra.app/Contents/Resources/app.asar/dist/main/main.js:2:447541)
at Object.5533 (/private/var/folders/jy/v11m1wcx015dg8vryv8fcdy80000gn/T/AppTranslocation/D9BF59BE-C131-4919-A5CD-9B0B3E1DCCA7/d/litra.app/Contents/Resources/app.asar/dist/main/main.js:2:446430)
at r (/private/var/folders/jy/v11m1wcx015dg8vryv8fcdy80000gn/T/AppTranslocation/D9BF59BE-C131-4919-A5CD-9B0B3E1DCCA7/d/litra.app/Contents/Resources/app.asar/dist/main/main.js:2:461750)
at /private/var/folders/jy/v11m1wcx015dg8vryv8fcdy80000gn/T/AppTranslocation/D9BF59BE-C131-4919-A5CD-9B0B3E1DCCA7/d/litra.app/Contents/Resources/app.asar/dist/main/main.js:2:461919
at Object.<anonymous> (/private/var/folders/jy/v11m1wcx015dg8vryv8fcdy80000gn/T/AppTranslocation/D9BF59BE-C131-4919-A5CD-9B0B3E1DCCA7/d/litra.app/Contents/Resources/app.asar/dist/main/main.js:2:461949)
at Module._compile (node:internal/modules/cjs/loader:1116:14)
at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
at Module.load (node:internal/modules/cjs/loader:988:32)`

**Comment by R-E-T** [comment]
Similar issue running on Win11:

Error: LIBUSB_ERROR_NOT_SUPPORTED
    at Interface.isKernelDriverActive (C:\Users\user\AppData\Local\Programs\litra\resources\app.asar\node_modules\usb\tsc\usb\interface.ts:118:28)
    at new t.default (C:\Users\user\AppData\Local\Programs\litra\resources\app.asar\dist\main\main.js:2:443533)
    at Object.t.create (C:\Users\user\AppData\Local\Programs\litra\resources\app.asar\dist\main\main.js:2:447541)
    at Object.5533 (C:\Users\user\AppData\Local\Programs\litra\resources\app.asar\dist\main\main.js:2:446430)
    at r (C:\Users\user\AppData\Local\Programs\litra\resources\app.asar\dist\main\main.js:2:461750)
    at C:\Users\user\AppData\Local\Programs\litra\resources\app.asar\dist\main\main.js:2:461919
    at Object.<anonymous> (C:\Users\user\AppData\Local\Programs\litra\resources\app.asar\dist\main\main.js:2:461949)
    at Module._compile (node:internal/modules/cjs/loader:1116:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1169:10)
    at Module.load (node:internal/modules/cjs/loader:988:32)

**Comment by 3axap4eHko** [comment]
@h-teske please try version [0.0.3](https://github.com/zource-dev/litra-glow/releases/tag/v0.0.3)

@R-E-T on Win11 this is something about USB drivers maybe (maybe not) driver installation via  [Zadig](https://zadig.akeo.ie/) would help

**Comment by tedall** [comment]
The new version 0.0.3 starts on Win11 without error messages. But it still does not work, either with or without the replacement driver via Zadig.
